using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DatabaseAnalyzer.DatabaseActions.Queries
{
    public static class SQLQueries
    {
        public static string Query_UserDefinedTypes { get; } = "SELECT  USRTPS.name AS 'TYPE_NAME', SCHMS.schema_id AS 'SCHEMA_ID', SCHMS.name AS 'SCHEMA_NAME', SYSTPS.name AS 'BASE_TYPE_NAME', CASE  WHEN USRTPS.precision = 0 AND USRTPS.scale = 0 THEN CAST(USRTPS.max_length AS nvarchar(100))  ELSE CONCAT(USRTPS.PRECISION,', ',USRTPS.scale) END AS 'PRECISION', USRTPS.is_nullable AS 'NULLABLE',  CASE  WHEN USRTPS.default_object_id <> 0 THEN SUBSTRING(DEFVAL.definition, 3, LEN(DEFVAL.definition)-4)  ELSE '' END AS 'DEFAULT_VALUE'  FROM sys.types USRTPS JOIN sys.schemas SCHMS ON USRTPS.schema_id = SCHMS.schema_id JOIN sys.types SYSTPS ON USRTPS.system_type_id = SYSTPS.system_type_id AND USRTPS.system_type_id = SYSTPS.user_type_id LEFT JOIN sys.default_constraints DEFVAL ON USRTPS.default_object_id = DEFVAL.object_id WHERE USRTPS.is_table_type = 0 AND USRTPS.is_user_defined = 1";
        public static string Query_UserDefinedTables { get; } = "SELECT	TABLEVIEW.name AS 'TABLE_NAME',	TABLEVIEW.schema_id 'SCHEMA_ID',	SCHMS.name AS 'SCHEMA_NAME',	COLS.name AS 'COLUMN_NAME',		CASE 	 WHEN COLS.system_type_id = COLS.user_type_id THEN SYSTYPE.name	 ELSE USRTYPE.name 	END AS 'TYPE_NAME',	CASE	 WHEN COLS.precision = 0 AND COLS.scale = 0 THEN CAST(COLS.max_length AS nvarchar(100))	 ELSE CONCAT(COLS.PRECISION,', ',COLS.scale)	END AS 'PRECISION',		COLS.is_nullable AS 'NULLABLE',	CASE	 WHEN COLS.default_object_id <> 0 THEN SUBSTRING(DEFVALUE.definition, 3, LEN(DEFVALUE.definition)-4)	 ELSE ''	END AS 'DEFAULT_VALUE'			 FROM sys.all_columns COLS		JOIN sys.table_types TABLEVIEW ON TABLEVIEW.type_table_object_id = COLS.object_id	JOIN sys.schemas SCHMS ON TABLEVIEW.schema_id = SCHMS.schema_id		JOIN sys.types SYSTYPE ON COLS.system_type_id = SYSTYPE.system_type_id AND COLS.system_type_id = SYSTYPE.user_type_id	LEFT JOIN sys.types USRTYPE ON COLS.system_type_id = USRTYPE.system_type_id AND COLS.user_type_id = USRTYPE.user_type_id	LEFT JOIN sys.default_constraints DEFVALUE ON COLS.default_object_id = DEFVALUE.object_id";
        public static string Query_Exeuctables { get; } = ";WITH PF AS	(	 SELECT object_id, name, schema_id, 'P' AS 'TYPE' FROM sys.procedures		 UNION ALL 		 SELECT object_id, name, schema_id, 'F' FROM sys.all_objects WHERE TYPE IN ('IF','TF','FN')	)		SELECT	PF.TYPE 'TYPE',	PF.name AS 'NAME',	PF.schema_id 'SCHEMA_ID',	SCHMS.name AS 'SCHEMA_NAME',	CASE	 WHEN PARAMS.is_output = 1 THEN '@RETURNS'	 ELSE PARAMS.name	END AS 'PARAM_NAME',		CASE 	 WHEN PARAMS.system_type_id = PARAMS.user_type_id THEN SYSTYPE.name	 ELSE USRTYPE.name 	END AS 'TYPE_NAME',		CASE	 WHEN PARAMS.precision = 0 AND PARAMS.scale = 0 THEN CAST(PARAMS.max_length AS nvarchar(100))	 ELSE CONCAT(PARAMS.PRECISION,', ',PARAMS.scale)	END AS 'PRECISION',		PARAMS.is_nullable AS 'NULLABLE',		USRTYPE.is_table_type AS 'IS_TABLE'		FROM sys.all_parameters PARAMS		LEFT JOIN PF ON PF.object_id = PARAMS.object_id	JOIN sys.schemas SCHMS ON PF.schema_id = SCHMS.schema_id		JOIN sys.types SYSTYPE ON PARAMS.system_type_id = SYSTYPE.system_type_id AND PARAMS.system_type_id = SYSTYPE.user_type_id	LEFT JOIN sys.types USRTYPE ON PARAMS.system_type_id = USRTYPE.system_type_id AND PARAMS.user_type_id = USRTYPE.user_type_id";
        public static string Query_DataContainers { get; } = ";WITH TABLEVIEW AS	(	SELECT 		'T' as 'type',		object_id,		name,		schema_id,		type_desc	FROM sys.tables		UNION		SELECT 		'V' as 'type',		object_id,		name,		schema_id,		type_desc	FROM sys.views	)		SELECT	TABLEVIEW.TYPE 'TABLE_TYPE',	TABLEVIEW.name AS 'TABLE_NAME',	TABLEVIEW.schema_id 'SCHEMA_ID',	SCHMS.name AS 'SCHEMA_NAME',	COLS.name AS 'COLUMN_NAME',		CASE 		WHEN COLS.system_type_id = COLS.user_type_id THEN SYSTYPE.name		ELSE USRTYPE.name 	END AS 'TYPE_NAME',	CASE		WHEN COLS.precision = 0 AND COLS.scale = 0 THEN CAST(COLS.max_length AS nvarchar(100))		ELSE CONCAT(COLS.PRECISION,', ',COLS.scale)	END AS 'PRECISION',		COLS.is_nullable AS 'NULLABLE',	CASE		WHEN COLS.default_object_id <> 0 THEN SUBSTRING(DEFVALUE.definition, 3, LEN(DEFVALUE.definition)-4)		ELSE ''	END AS 'DEFAULT_VALUE'			 FROM sys.all_columns COLS		JOIN TABLEVIEW ON TABLEVIEW.object_id = COLS.object_id	JOIN sys.schemas SCHMS ON TABLEVIEW.schema_id = SCHMS.schema_id		JOIN sys.types SYSTYPE ON COLS.system_type_id = SYSTYPE.system_type_id AND COLS.system_type_id = SYSTYPE.user_type_id	LEFT JOIN sys.types USRTYPE ON COLS.system_type_id = USRTYPE.system_type_id AND COLS.user_type_id = USRTYPE.user_type_id    LEFT JOIN sys.default_constraints DEFVALUE ON COLS.default_object_id = DEFVALUE.object_id";
    }
}
